services:
  - type: web
    name: vet-clin-path-mcq
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NCBI_API_KEY
        sync: false
      - key: NCBI_EMAIL
        sync: false
